### PR TITLE
Fix incorrect "global context" handling

### LINKED ISSUE #24: `series` variable is not present in the global context
When trying to reference `series` in a template page in `TEMPLATE_PAGES`, I get the jinja error
`UndefinedError: 'series' is undefined`
I don't see a test for this either.

This probably needs to go under `all_generators_finalized`, since `article_generator_finalized` only processes article generators, not page generators.

### PR DESCRIPTION
**Pull request by GiovanH**
Resolves #24

### CODE REVIEW

**Comment by GiovanH** [comment]
No idea what's wrong with that build step but it's not related to the change.

**Comment by lgiordani** [comment]
Thanks! I will review asap

**Comment by justinmayer** [comment]
@GiovanH: Thanks for the submission. Don't worry about the pre-commit.ci error, which I believe I resolved in the `main` branch. Once @lgiordani has reviewed the changes, and this PR is ready to merge, we can use the **Update branch** button (which I just enabled on this repo) to rebase this PR on `main` and pick up those aforementioned improvements.

**Review by justinmayer — CHANGES_REQUESTED** [review]
@GiovanH: That said, there is one linter issue that needs resolving, which I marked in the `series.py` file you changed.

**Comment by justinmayer** [comment]
Checks are all green here, so this PR can be merged once @lgiordani has a moment to review it.

**Review by lgiordani — APPROVED** [review]

**Comment by lgiordani** [comment]
@GiovanH apologies for the long time it took me to have a look!

**Pull request merged**
